# Generated by Django 4.2.9 on 2024-01-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_user_user_name_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
